const services={
 'pedicure-medical':{title:'Pedicure Medical',kicker:'Especialidade',duration:'sob avaliação',price:'consultar',intro:'Um cuidado técnico e personalizado para pés e unhas, pensado para quem procura mais atenção ao detalhe e ao conforto.',benefits:['Cuidado detalhado da pele e das unhas','Sensação de conforto e bem-estar nos pés','Atenção individual às necessidades apresentadas'],recommendation:'Pode ser a melhor escolha quando o objetivo é dedicar mais atenção aos pés ou quando existe uma necessidade específica a avaliar.'},
 pedicure:{title:'Pedicure',kicker:'Pés',duration:'sob consulta',price:'consultar',intro:'Um cuidado completo para manter os pés tratados, apresentáveis e confortáveis.',benefits:['Higiene e cuidado das unhas','Cuidado das cutículas e da pele','Acabamento bonito e sensação de leveza'],recommendation:'Ideal para manutenção regular ou quando pretende voltar a cuidar dos pés com calma.'},
 manicure:{title:'Manicure',kicker:'Mãos',duration:'sob consulta',price:'consultar',intro:'Um tratamento dedicado às mãos e unhas, com acabamento delicado e atenção às cutículas.',benefits:['Unhas cuidadas e uniformes','Cutículas tratadas','Acabamento elegante e sensação de cuidado'],recommendation:'Uma boa escolha para manutenção das unhas ou antes de uma ocasião especial.'},
 facial:{title:'Limpeza de Pele',kicker:'Rosto',duration:'sob consulta',price:'consultar',intro:'Um cuidado facial focado em limpeza, equilíbrio e sensação de pele renovada.',benefits:['Limpeza e higienização da pele','Sensação de frescura e luminosidade','Momento de cuidado e relaxamento'],recommendation:'Indicada quando sente a pele sobrecarregada, sem viço ou quando procura uma rotina de cuidado mais completa.'},
 massagem:{title:'Massagens',kicker:'Bem-estar',duration:'sob consulta',price:'consultar',intro:'Um momento dedicado a desacelerar, relaxar e devolver leveza ao corpo.',benefits:['Ajuda a promover relaxamento','Pode proporcionar sensação de alívio de tensão','Tempo de pausa e bem-estar'],recommendation:'Uma escolha natural quando o principal objetivo é parar, respirar e cuidar do corpo.'},
 depilacao:{title:'Depilação',kicker:'Pele',duration:'varia por zona',price:'consultar',intro:'Opções de depilação para diferentes zonas, realizadas com atenção ao conforto e à pele.',benefits:['Cuidado direcionado à zona escolhida','Sensação de pele mais lisa','Atendimento adaptado ao procedimento'],recommendation:'A escolha depende da zona e do método disponível. O ideal é selecionar primeiro a área que pretende tratar.'}
};
const reviews=[
 ['Tom','TS','“Muito profissional, gostei muito do atendimento, lugar agradável, tranquilo e serviço de qualidade. Recomendo muito.”'],
 ['Orlando P','OP','“Que se pode dizer... além do tratamento magnífico que nos proporciona também ajuda a alma. Gleivia fantástica como profissional e como pessoa.”'],
 ['Isadora','IS','“Estou muito feliz e satisfeita mais uma vez com o serviço! És incrivelmente maravilhosa Gleivia.”'],
 ['António V','AV','“Excelente profissional, sempre cuidadosa e muito atenta ao que faz e com as melhores dicas e técnicas.”']
];
const bookingServices=[
 {id:'pedicure-calista',name:'Pedicure Calista',duration:90,price:45},
 {id:'pedicure-tradicional',name:'Pedicure Tradicional',duration:60,price:30},
 {id:'manicure-simples',name:'Manicure Simples',duration:40,price:15},
 {id:'premium',name:'Premium',duration:90,price:50},
 {id:'massagem',name:'Massagem',duration:60,price:35},
 {id:'depilacao',name:'Depilação',duration:30,price:30}
];
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const escapeHtml=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));

// Portrait uploaded by the user: stored as encoded asset so the project does not depend on a signed external image URL.
fetch('assets/gleivia-about.webp.b64').then(r=>r.text()).then(b64=>{const img=$('#gleiviaPortrait');if(img)img.src='data:image/webp;base64,'+b64.trim()}).catch(()=>{});

// Graceful image fallback: never show broken-image icons in the proposal.
$$('img').forEach(img=>img.addEventListener('error',()=>{if(img.dataset.failed)return;img.dataset.failed='1';img.src='data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 600"><rect width="100%" height="100%" fill="#e6ddd5"/><text x="50%" y="50%" text-anchor="middle" font-family="Georgia" font-size="30" fill="#796b63">Gleivia Silva Estética</text></svg>`)}));

// Reveal motion.
const revealEls=$$('.reveal,.service-card,.portfolio-item');const revealObs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');revealObs.unobserve(e.target)}}),{threshold:.08});revealEls.forEach(e=>revealObs.observe(e));

function openOverlay(html,klass='site-modal'){const wrap=document.createElement('div');wrap.className=klass;wrap.innerHTML=html;document.body.appendChild(wrap);requestAnimationFrame(()=>wrap.classList.add('open'));const close=()=>{wrap.classList.remove('open');setTimeout(()=>wrap.remove(),220)};wrap.addEventListener('click',e=>{if(e.target===wrap||e.target.closest('[data-close]'))close()});document.addEventListener('keydown',function esc(e){if(e.key==='Escape'){close();document.removeEventListener('keydown',esc)}},{once:true});return wrap}

function openService(id){const s=services[id];if(!s)return;openOverlay(`<div class="detail-dialog"><button class="modal-close" data-close>×</button><span class="modal-kicker">${s.kicker}</span><h2>${s.title}</h2><p class="detail-lead">${s.intro}</p><div class="detail-grid"><div><small>DURAÇÃO</small><strong>${s.duration}</strong></div><div><small>VALOR</small><strong>${s.price}</strong></div></div><h3>Benefícios e objetivos</h3><ul>${s.benefits.map(x=>`<li>${x}</li>`).join('')}</ul><div class="recommendation-box"><small>RECOMENDAÇÃO</small><p>${s.recommendation}</p></div><button class="button button-dark js-booking-inside"><span class="icon icon-calendar"></span>Escolher para agendar <strong>→</strong></button></div>`);wrapBookingButton();}
$$('.js-service').forEach(b=>b.addEventListener('click',()=>openService(b.dataset.service)));
$('.js-service-list')?.addEventListener('click',()=>openOverlay(`<div class="list-dialog"><button class="modal-close" data-close>×</button><span class="modal-kicker">Catálogo</span><h2>Tratamentos disponíveis</h2><p>Uma demonstração do catálogo que pode existir no site final, antes do passo de agendamento.</p><div class="catalog-grid">${['Pedicure Calista','Pedicure Tradicional','Manicure Simples','Limpeza de Pele Premium','Massagem Corporal','Massagem Facial','Depilação a Cera','Depilação a Laser','Zona L','Zona XXL','Virilha Cavada','Pedicure e Manicure'].map((x,i)=>`<button class="catalog-row js-catalog" data-name="${escapeHtml(x)}"><span>${String(i+1).padStart(2,'0')}</span><strong>${x}</strong><i>↗</i></button>`).join('')}</div></div>`));

function wrapBookingButton(){document.querySelectorAll('.js-booking-inside').forEach(b=>b.onclick=()=>{b.closest('.site-modal')?.remove();openBooking()})}

// Recommendation quiz.
function openQuiz(){const box=openOverlay(`<div class="quiz-dialog"><button class="modal-close" data-close>×</button><span class="modal-kicker">Orientação personalizada</span><h2>Vamos descobrir por onde começar.</h2><p>Responda a três perguntas. No final, mostramos um ponto de partida possível — não substitui uma avaliação profissional.</p><div id="quizBody"></div></div>`);const body=$('#quizBody',box);const answers={goal:null,feel:null,priority:null};let step=0;const questions=[{key:'goal',title:'O que gostaria de cuidar hoje?',opts:[['pés','Pés e unhas'],['mãos','Mãos e unhas'],['pele','Rosto e pele'],['corpo','Corpo e relaxamento']]},{key:'feel',title:'O que mais procura neste momento?',opts:[['cuidado','Manutenção e cuidado'],['resultado','Sentir a pele/unhas mais cuidadas'],['relaxar','Relaxar e aliviar tensão']]},{key:'priority',title:'Prefere um atendimento...',opts:[['tecnico','Mais focado numa necessidade específica'],['suave','Mais relaxante e tranquilo'],['completo','Com uma abordagem mais completa']]}];const render=()=>{const q=questions[step];body.innerHTML=`<div class="quiz-step"><span>0${step+1} / 03</span><h3>${q.title}</h3><div class="quiz-options">${q.opts.map(([v,l])=>`<button data-v="${v}">${l}<i>→</i></button>`).join('')}</div></div>`;body.querySelectorAll('button').forEach(btn=>btn.onclick=()=>{answers[q.key]=btn.dataset.v;if(step<questions.length-1){step++;render()}else result()})};const result=()=>{let picks;if(answers.goal==='pés')picks=['Pedicure Medical','Pedicure Tradicional'];else if(answers.goal==='mãos')picks=['Manicure Simples','Pedicure e Manicure'];else if(answers.goal==='pele')picks=['Limpeza de Pele Premium'];else picks=['Massagem Corporal','Massagem Facial'];box.querySelector('.quiz-dialog').classList.add('result');body.innerHTML=`<div class="quiz-result"><span class="modal-kicker">Possível ponto de partida</span><h3>Pelo que descreveu, estes cuidados podem fazer sentido:</h3><div>${picks.map(p=>`<button class="result-option js-result" data-name="${p}"><strong>${p}</strong><span>Conhecer e agendar →</span></button>`).join('')}</div><small>O resultado é apenas orientativo. A escolha final deve considerar as necessidades avaliadas pela profissional.</small></div>`;body.querySelectorAll('.js-result').forEach(b=>b.onclick=()=>{box.remove();openBooking(b.dataset.name)})};render();}
$('#openQuiz')?.addEventListener('click',openQuiz);$('#openQuiz2')?.addEventListener('click',openQuiz);

// Portfolio filter.
$$('.portfolio-nav button').forEach(btn=>btn.addEventListener('click',()=>{$$('.portfolio-nav button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.filter;$$('.portfolio-item').forEach(item=>item.style.display=f==='all'||item.dataset.cat===f?'':'none')}));

// Reviews.
let reviewIndex=0;function renderReview(){const [name,initials,text]=reviews[reviewIndex];$('#reviewName').textContent=name;$('#reviewText').textContent=text;$('#reviewIndex').textContent=`0${reviewIndex+1} / 04`;const av=$('.avatar');if(av)av.textContent=initials}$('#reviewNext')?.addEventListener('click',()=>{reviewIndex=(reviewIndex+1)%reviews.length;renderReview()});$('#reviewPrev')?.addEventListener('click',()=>{reviewIndex=(reviewIndex-1+reviews.length)%reviews.length;renderReview()});

// Demo booking flow.
let selectedService=null,selectedDate=null,selectedTime=null;const storeKey='gleivia-demo-bookings';
function demoDates(){const arr=[];const d=new Date();d.setHours(0,0,0,0);for(let i=1;i<24;i++){const x=new Date(d);x.setDate(d.getDate()+i);if(x.getDay()!==0)arr.push(x)}return arr}
function openBooking(preset=''){selectedService=bookingServices.find(x=>x.name.toLowerCase()===preset.toLowerCase())||bookingServices[0];selectedDate=demoDates()[0];selectedTime=null;const modal=openOverlay(`<div class="booking-dialog"><button class="modal-close" data-close>×</button><div class="booking-left"><span class="modal-kicker">Agendamento</span><h2>Reserve o seu<br><em>momento.</em></h2><p>Uma demonstração da experiência de marcação que pode ficar integrada no site.</p><h3>1 · Escolha o tratamento</h3><div class="booking-services">${bookingServices.map(s=>`<button class="booking-choice ${s.id===selectedService.id?'selected':''}" data-id="${s.id}"><strong>${s.name}</strong><span>${s.duration} min · €${s.price}</span></button>`).join('')}</div><h3>2 · Escolha o dia</h3><div class="booking-dates"></div><div class="booking-times"></div></div><div class="booking-right"><span class="modal-kicker">Resumo</span><div class="booking-summary"><h3 class="sum-service"></h3><p class="sum-date"></p><p class="sum-time"></p><div class="booking-form"><input id="bookName" placeholder="Nome completo"><input id="bookPhone" placeholder="Telefone / WhatsApp"><input id="bookEmail" placeholder="Email"><button class="button button-dark" id="confirmBooking"><span class="icon icon-calendar"></span>Confirmar pedido <strong>→</strong></button></div><small>Demo: esta reserva não é enviada para uma base de dados nesta proposta. O fluxo está preparado para receber backend quando o site for contratado.</small></div></div></div>`);
const renderSummary=()=>{modal.querySelector('.sum-service').textContent=selectedService.name;modal.querySelector('.sum-date').textContent=selectedDate?pretty(selectedDate):'Escolha uma data';modal.querySelector('.sum-time').textContent=selectedTime||'Escolha uma hora'};const pretty=d=>new Intl.DateTimeFormat('pt-PT',{weekday:'long',day:'numeric',month:'long'}).format(d);
const renderDates=()=>{modal.querySelector('.booking-dates').innerHTML=demoDates().slice(0,10).map((d,i)=>`<button class="date-choice ${selectedDate?.toDateString()===d.toDateString()?'selected':''}" data-i="${i}"><span>${new Intl.DateTimeFormat('pt-PT',{weekday:'short'}).format(d).replace('.','')}</span><strong>${d.getDate()}</strong><small>${new Intl.DateTimeFormat('pt-PT',{month:'short'}).format(d)}</small></button>`).join('');modal.querySelectorAll('.date-choice').forEach(b=>b.onclick=()=>{selectedDate=demoDates()[+b.dataset.i];selectedTime=null;renderDates();renderTimes();renderSummary()})};
const renderTimes=()=>{const times=['10:00','10:30','11:00','11:30','14:00','14:30','15:00','15:30','16:00','17:00','17:30','18:00'];modal.querySelector('.booking-times').innerHTML=times.map(t=>`<button class="time-choice ${selectedTime===t?'selected':''}" data-t="${t}">${t}</button>`).join('');modal.querySelectorAll('.time-choice').forEach(b=>b.onclick=()=>{selectedTime=b.dataset.t;renderTimes();renderSummary()})};
modal.querySelectorAll('.booking-choice').forEach(b=>b.onclick=()=>{selectedService=bookingServices.find(s=>s.id===b.dataset.id);modal.querySelectorAll('.booking-choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selectedTime=null;renderSummary();renderTimes()});renderDates();renderTimes();renderSummary();modal.querySelector('#confirmBooking').onclick=()=>{const name=$('#bookName',modal)?.value.trim();const phone=$('#bookPhone',modal)?.value.trim();const email=$('#bookEmail',modal)?.value.trim();if(!name||!phone||!email||!selectedDate||!selectedTime){alert('Preencha os dados e escolha data e horário.');return}localStorage.setItem(storeKey,JSON.stringify({name,phone,email,service:selectedService.name,date:selectedDate.toISOString(),time:selectedTime}));modal.querySelector('.booking-dialog').innerHTML=`<div class="booking-confirmed"><span class="modal-kicker">Pedido recebido</span><h2>Até breve, ${escapeHtml(name.split(' ')[0])}.</h2><p>O fluxo de agendamento está concluído nesta demonstração.</p><div class="confirmation-code">${selectedService.name}<br>${pretty(selectedDate)} · ${selectedTime}</div><button class="button button-dark" data-close>Fechar</button></div>`};return modal}
$$('.js-booking').forEach(b=>b.addEventListener('click',()=>openBooking()));

// Load the actual user-provided portrait after DOM is ready.
const portrait=$('#gleiviaPortrait');if(portrait&&!portrait.src)fetch('assets/gleivia-about.webp.b64').then(r=>r.text()).then(b=>{portrait.src='data:image/webp;base64,'+b.trim()}).catch(()=>{});
